# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 227fe15fbb921f745f7272839d81700ce8816b12bcdf6008ec904763f6504c1e634e07e1018882330e0c5704983b0153ff1b40dc95d084d1f368b8e6462599e3

test:
  secret_key_base: 68504d4fb59f0214faca0ee125a386185e7e2ab1f77183f01f896a1fc2e63f58a8fb150b80c972e705418675a4988d2881ad999fe6a00e472fdd81db4bc7bac2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
